### ISSUE TITLE
Add GMQE as template selection metric

### ISSUE THREAD

**Issue by wt12318** [PhilippJunk/homelette#3]
Hi,

Is possible to calculate GMQE (https://swissmodel.expasy.org/docs/help#GMQE ) before modeling ?. It is useful for template selection.

Thanks.

**Comment by PhilippJunk** [comment]
Hi, 

GMQE is currently not implemented in the `homelette` package. Additionally, to the best of my knowledge, the source code for the calculation of GMQE does not seem to be available, so it will be difficult to integrate.

In general, `homelette` should be relatively easily extendable with custom routines, especially if they are implemented in python. A way to approach this would be to write a custom `Alignment_Generator` object (having it inherit from one of the existing ones if needed) and include a method for selection by some metric.
